---
  
package_manager: yum
nodejs_version: v0.10.4
ruby_version: 2.3.1
rails_version: 5.0.0.1
java_version: 1.8.0
blacklight_version: 6.7.1
domainname: localhost
app_name: blsearch
app_path: /var/www/{{ app_name }}
app_repo: https://github.com/skng5/blsearch
