## Add the app users
- group: name=devs state=present
- file: path=/home/{{ app_user }}/.bashrc owner={{ app_user }} group={{ app_user }} mode=0755
- file: path=/home/{{ app_user }}/.bash_profile owner={{ app_user }} group={{ app_user }} mode=0755
