---
# Install app gems
#
- name: Clone Blacklight Application
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"
    force: yes
- name: Change directory attributes
  file:
    path: "{{ app_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755
    recurse: yes
    state: directory
- name: Install Ruby gems
  command: "/home/{{ app_user }}/.rbenv/shims/bundle install"
  args:
    chdir: "{{ app_path }}"
  remote_user: "{{ app_user }}"
- template:
    src: templates/secrets.yml
    dest: "{{ app_path }}/config"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755
- name: Migrate database
  command: "/home/{{ app_user }}/.rbenv/shims/rake db:migrate"
  args:
    chdir: "{{ app_path }}"
  remote_user: "{{ app_user }}"
- name: Generate clean Solr
  command: "/home/{{ app_user }}/.rbenv/shims/rake solr:clean"
  args:
    chdir: "{{ app_path }}"
  remote_user: "{{ app_user }}"
- name: Install foreman
  command: "/home/{{ app_user }}/.rbenv/shims/gem install foreman --no-ri"
  remote_user: "{{ app_user }}"
- name: Copy Procfile
  copy:
    src: files/Procfile
    dest: "{{ app_path }}"
    mode: 0755
  remote_user: "{{ app_user }}"
