version: "1"
defaults:
  app_name: blsearch
services:
  blsearch:
    image: centos:7
    ports:
      - "3000:3000"
      - "8983:8983"
    command: ["/usr/bin/dumb-init", "/bin/bash"]
    working_dir: "/var/www/{{ app_name }}"
    dev_overrides:
      environment:
        - "DEBUG=1"
      command: ["/usr/bin/dumb-init", '/home/{{ app_name }}/.rbenv/shims/foreman', 'start']
registries: {}
