---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    package_manager: yum
    nodejs_version: v0.10.4
    ruby_version: 2.3.1
    rails_version: 5.0.0.1
    java_version: 1.8.0
    blacklight_version: 6.7.1
    domainname: localhost
    app_name: blsearch
    app_user: vagrant
    app_path: /var/www/{{ app_name }}
  tasks:
    - include: tasks/devtools.yml
    - include: tasks/java.yml
    - include: tasks/maven.yml
    - include: tasks/nodejs.yml
    - include: tasks/ruby.yml
      become : "{{ app_user }}"
#    - include: tasks/blacklight.yml
#      become : "{{ app_user }}"
